version: "3"

vars:
  image: akhmanov/airc
  go_version: 1.26.4
  tag: go{{.go_version}}

tasks:
  build: >-
    docker build
    -t {{.image}}:{{.tag}}
    -t {{.image}}:latest
    -f ./Dockerfile .

  buildx: >-
    docker run --privileged --rm tonistiigi/binfmt --install all &&
    docker buildx create --name airc &&
    docker buildx use airc &&
    docker buildx inspect --bootstrap

  push: >-
    docker buildx build
    --platform linux/amd64,linux/arm64,linux/arm/v7
    -t {{.image}}:{{.tag}}
    -t {{.image}}:latest
    -f ./Dockerfile
    --push .
